# Generated by Django 4.2 on 2024-01-03 16:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cadre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='post/%y')),
                ('description', models.CharField(max_length=255)),
                ('format', models.CharField(choices=[('format A4(20cm X 30cm)', 'format A4(20cm X 30cm)'), ('format A3(30cm X 40cm)', 'format A3(30cm X 40cm)'), ('format A2(40cm X 60cm)', 'format A2(40cm X 60cm)'), ('format A1(60cm X 100cm)', 'format A1(60cm X 100cm)')], max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('numero', models.CharField(max_length=255)),
                ('residence', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='reservation/%y')),
                ('format', models.CharField(choices=[('format A4(20cm X 30cm)', 'format A4(20cm X 30cm)'), ('format A3(30cm X 40cm)', 'format A3(30cm X 40cm)'), ('format A2(40cm X 60cm)', 'format A2(40cm X 60cm)'), ('format A1(60cm X 100cm)', 'format A1(60cm X 100cm)')], max_length=255)),
                ('event', models.CharField(max_length=255)),
                ('date', models.DateField(auto_now=True)),
                ('date_remise', models.DateField(blank=True)),
                ('auth', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reservation',
                'ordering': ['-date'],
            },
        ),
    ]
