# Generated by Django 4.2 on 2024-01-03 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profiluser',
            name='motdepasse',
        ),
    ]
